//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for XmlAttributes complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlAttributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actionType" type="{urn:appsecinc.com/js-workflow-extensions}XmlActionType"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="task" type="{urn:appsecinc.com/js-workflow-extensions}XmlTask" minOccurs="0"/>
 *         &lt;element name="parameter" type="{urn:appsecinc.com/js-workflow-extensions}XmlParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="timeout" type="{urn:appsecinc.com/js-workflow-extensions}XmlTimeout" minOccurs="0"/>
 *         &lt;element name="output" type="{urn:appsecinc.com/js-workflow-extensions}XmlOutput" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="onEvent" type="{urn:appsecinc.com/js-workflow-extensions}XmlEventDescriptor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="selectArc" type="{urn:appsecinc.com/js-workflow-extensions}XmlSelectArc" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlAttributes", propOrder = {
        "actionType",
        "description",
        "task",
        "parameter",
        "timeout",
        "output",
        "onEvent",
        "selectArc"
})
public class XmlAttributes
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected XmlActionType actionType;
    protected String description;
    protected XmlTask task;
    protected List<XmlParameter> parameter;
    protected XmlTimeout timeout;
    protected List<XmlOutput> output;
    protected List<XmlEventDescriptor> onEvent;
    protected List<XmlSelectArc> selectArc;

    /**
     * Gets the value of the actionType property.
     *
     * @return possible object is
     * {@link XmlActionType }
     */
    public XmlActionType getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     *
     * @param value allowed object is
     * {@link XmlActionType }
     */
    public void setActionType(XmlActionType value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the task property.
     *
     * @return possible object is
     * {@link XmlTask }
     */
    public XmlTask getTask() {
        return task;
    }

    /**
     * Sets the value of the task property.
     *
     * @param value allowed object is
     * {@link XmlTask }
     */
    public void setTask(XmlTask value) {
        this.task = value;
    }

    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlParameter }
     */
    public List<XmlParameter> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<XmlParameter>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the timeout property.
     *
     * @return possible object is
     * {@link XmlTimeout }
     */
    public XmlTimeout getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     *
     * @param value allowed object is
     * {@link XmlTimeout }
     */
    public void setTimeout(XmlTimeout value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the output property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlOutput }
     */
    public List<XmlOutput> getOutput() {
        if (output == null) {
            output = new ArrayList<XmlOutput>();
        }
        return this.output;
    }

    /**
     * Gets the value of the onEvent property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onEvent property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnEvent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlEventDescriptor }
     */
    public List<XmlEventDescriptor> getOnEvent() {
        if (onEvent == null) {
            onEvent = new ArrayList<XmlEventDescriptor>();
        }
        return this.onEvent;
    }

    /**
     * Gets the value of the selectArc property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectArc property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectArc().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlSelectArc }
     */
    public List<XmlSelectArc> getSelectArc() {
        if (selectArc == null) {
            selectArc = new ArrayList<XmlSelectArc>();
        }
        return this.selectArc;
    }

}
