//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for XmlExitCondition.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="XmlExitCondition">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OK"/>
 *     &lt;enumeration value="ServiceNotAvailable"/>
 *     &lt;enumeration value="InvalidCredentials"/>
 *     &lt;enumeration value="Authorization"/>
 *     &lt;enumeration value="NotSupported"/>
 *     &lt;enumeration value="ResourceNotAvailable"/>
 *     &lt;enumeration value="Timeout"/>
 *     &lt;enumeration value="Canceled"/>
 *     &lt;enumeration value="WorkflowError"/>
 *     &lt;enumeration value="GeneralFailure"/>
 *     &lt;enumeration value="EmptyTokenset"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "XmlExitCondition")
@XmlEnum
public enum XmlExitCondition {

    OK("OK"),
    @XmlEnumValue("ServiceNotAvailable")
    SERVICE_NOT_AVAILABLE("ServiceNotAvailable"),
    @XmlEnumValue("InvalidCredentials")
    INVALID_CREDENTIALS("InvalidCredentials"),
    @XmlEnumValue("Authorization")
    AUTHORIZATION("Authorization"),
    @XmlEnumValue("NotSupported")
    NOT_SUPPORTED("NotSupported"),
    @XmlEnumValue("ResourceNotAvailable")
    RESOURCE_NOT_AVAILABLE("ResourceNotAvailable"),
    @XmlEnumValue("Timeout")
    TIMEOUT("Timeout"),
    @XmlEnumValue("Canceled")
    CANCELED("Canceled"),
    @XmlEnumValue("WorkflowError")
    WORKFLOW_ERROR("WorkflowError"),
    @XmlEnumValue("GeneralFailure")
    GENERAL_FAILURE("GeneralFailure"),
    @XmlEnumValue("EmptyTokenset")
    EMPTY_TOKENSET("EmptyTokenset");
    private final String value;

    XmlExitCondition(String v) {
        value = v;
    }

    public static XmlExitCondition fromValue(String v) {
        for (XmlExitCondition c : XmlExitCondition.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
