//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for XmlEventDescriptor complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlEventDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="output" type="{urn:appsecinc.com/js-workflow-extensions}XmlOutput" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="arc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="backTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="button" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="forceCompletion" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="cleanCondition" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlEventDescriptor", propOrder = {
        "output"
})
public class XmlEventDescriptor
        implements Serializable {

    private final static long serialVersionUID = 1L;
    protected List<XmlOutput> output;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "arc")
    protected String arc;
    @XmlAttribute(name = "backTo")
    protected String backTo;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "button")
    protected String button;
    @XmlAttribute(name = "forceCompletion")
    protected Boolean forceCompletion;
    @XmlAttribute(name = "cleanCondition")
    protected Boolean cleanCondition;

    /**
     * Gets the value of the output property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlOutput }
     */
    public List<XmlOutput> getOutput() {
        if (output == null) {
            output = new ArrayList<XmlOutput>();
        }
        return this.output;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the arc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getArc() {
        return arc;
    }

    /**
     * Sets the value of the arc property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setArc(String value) {
        this.arc = value;
    }

    /**
     * Gets the value of the backTo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBackTo() {
        return backTo;
    }

    /**
     * Sets the value of the backTo property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setBackTo(String value) {
        this.backTo = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the button property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getButton() {
        return button;
    }

    /**
     * Sets the value of the button property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setButton(String value) {
        this.button = value;
    }

    /**
     * Gets the value of the forceCompletion property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isForceCompletion() {
        if (forceCompletion == null) {
            return true;
        }
        else {
            return forceCompletion;
        }
    }

    /**
     * Sets the value of the forceCompletion property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setForceCompletion(Boolean value) {
        this.forceCompletion = value;
    }

    /**
     * Gets the value of the cleanCondition property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isCleanCondition() {
        if (cleanCondition == null) {
            return true;
        }
        else {
            return cleanCondition;
        }
    }

    /**
     * Sets the value of the cleanCondition property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setCleanCondition(Boolean value) {
        this.cleanCondition = value;
    }

}
