//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for XmlExtendedDescription complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlExtendedDescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flags" type="{urn:appsecinc.com/js-workflow-extensions}XmlFlags" minOccurs="0"/>
 *         &lt;element name="parameters" type="{urn:appsecinc.com/js-workflow-extensions}XmlParameters" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlExtendedDescription", propOrder = {
        "description",
        "flags",
        "parameters",
        "image"
})
public class XmlExtendedDescription
        implements Serializable {

    private final static long serialVersionUID = 1L;
    protected String description;
    protected XmlFlags flags;
    protected XmlParameters parameters;
    protected List<String> image;

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the flags property.
     *
     * @return possible object is
     * {@link XmlFlags }
     */
    public XmlFlags getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     *
     * @param value allowed object is
     * {@link XmlFlags }
     */
    public void setFlags(XmlFlags value) {
        this.flags = value;
    }

    /**
     * Gets the value of the parameters property.
     *
     * @return possible object is
     * {@link XmlParameters }
     */
    public XmlParameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     *
     * @param value allowed object is
     * {@link XmlParameters }
     */
    public void setParameters(XmlParameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the image property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getImage() {
        if (image == null) {
            image = new ArrayList<String>();
        }
        return this.image;
    }

}
