//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import java.io.Serializable;

/**
 * <p>Java class for XmlFlags complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlFlags">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="utilityJob" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="deleteCompletedInstanceAfter" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlFlags")
public class XmlFlags
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "utilityJob")
    protected Boolean utilityJob;
    @XmlAttribute(name = "deleteCompletedInstanceAfter")
    protected Duration deleteCompletedInstanceAfter;

    /**
     * Gets the value of the utilityJob property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isUtilityJob() {
        if (utilityJob == null) {
            return false;
        }
        else {
            return utilityJob;
        }
    }

    /**
     * Sets the value of the utilityJob property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setUtilityJob(Boolean value) {
        this.utilityJob = value;
    }

    /**
     * Gets the value of the deleteCompletedInstanceAfter property.
     *
     * @return possible object is
     * {@link Duration }
     */
    public Duration getDeleteCompletedInstanceAfter() {
        return deleteCompletedInstanceAfter;
    }

    /**
     * Sets the value of the deleteCompletedInstanceAfter property.
     *
     * @param value allowed object is
     * {@link Duration }
     */
    public void setDeleteCompletedInstanceAfter(Duration value) {
        this.deleteCompletedInstanceAfter = value;
    }

}
