//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * <p>Java class for XmlOutput complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="internalName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="override" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="clearValue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="env" type="{urn:appsecinc.com/js-workflow-extensions}XmlOutputEnv" default="token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlOutput")
public class XmlOutput
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "internalName")
    protected String internalName;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "value")
    protected String value;
    @XmlAttribute(name = "override")
    protected Boolean override;
    @XmlAttribute(name = "clearValue")
    protected Boolean clearValue;
    @XmlAttribute(name = "env")
    protected XmlOutputEnv env;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the internalName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInternalName() {
        return internalName;
    }

    /**
     * Sets the value of the internalName property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setInternalName(String value) {
        this.internalName = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the override property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isOverride() {
        if (override == null) {
            return false;
        }
        else {
            return override;
        }
    }

    /**
     * Sets the value of the override property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setOverride(Boolean value) {
        this.override = value;
    }

    /**
     * Gets the value of the clearValue property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isClearValue() {
        if (clearValue == null) {
            return false;
        }
        else {
            return clearValue;
        }
    }

    /**
     * Sets the value of the clearValue property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setClearValue(Boolean value) {
        this.clearValue = value;
    }

    /**
     * Gets the value of the env property.
     *
     * @return possible object is
     * {@link XmlOutputEnv }
     */
    public XmlOutputEnv getEnv() {
        if (env == null) {
            return XmlOutputEnv.TOKEN;
        }
        else {
            return env;
        }
    }

    /**
     * Sets the value of the env property.
     *
     * @param value allowed object is
     * {@link XmlOutputEnv }
     */
    public void setEnv(XmlOutputEnv value) {
        this.env = value;
    }

}
