//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for XmlParameters complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parameter" type="{urn:appsecinc.com/js-workflow-extensions}XmlParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="validator" type="{urn:appsecinc.com/js-workflow-extensions}XmlValidator" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="allJobParameters" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlParameters", propOrder = {
        "parameter",
        "validator"
})
public class XmlParameters
        implements Serializable {

    private final static long serialVersionUID = 1L;
    protected List<XmlParameter> parameter;
    protected List<XmlValidator> validator;
    @XmlAttribute(name = "allJobParameters")
    protected Boolean allJobParameters;

    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlParameter }
     */
    public List<XmlParameter> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<XmlParameter>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the validator property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validator property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidator().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlValidator }
     */
    public List<XmlValidator> getValidator() {
        if (validator == null) {
            validator = new ArrayList<XmlValidator>();
        }
        return this.validator;
    }

    /**
     * Gets the value of the allJobParameters property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isAllJobParameters() {
        if (allJobParameters == null) {
            return false;
        }
        else {
            return allJobParameters;
        }
    }

    /**
     * Sets the value of the allJobParameters property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setAllJobParameters(Boolean value) {
        this.allJobParameters = value;
    }

}
