//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for XmlParameter complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlParameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="selector" type="{urn:appsecinc.com/js-workflow-extensions}XmlSelector" minOccurs="0"/>
 *         &lt;element name="validator" type="{urn:appsecinc.com/js-workflow-extensions}XmlValidator" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="metadata" type="{urn:appsecinc.com/js-workflow-extensions}XmlNameValuePair" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="internalName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valuePresent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="override" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ignoreExpressionErrors" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="joinDiscriminator" type="{http://www.w3.org/2001/XMLSchema}string" default="item" />
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlParameter", propOrder = {
        "text",
        "selector",
        "validator",
        "metadata"
})
public class XmlParameter
        implements Serializable {

    private final static long serialVersionUID = 1L;
    protected String text;
    protected XmlSelector selector;
    protected List<XmlValidator> validator;
    protected List<XmlNameValuePair> metadata;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "internalName")
    protected String internalName;
    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "value")
    protected String value;
    @XmlAttribute(name = "valuePresent")
    protected Boolean valuePresent;
    @XmlAttribute(name = "override")
    protected Boolean override;
    @XmlAttribute(name = "defaultValue")
    protected String defaultValue;
    @XmlAttribute(name = "ignoreExpressionErrors")
    protected Boolean ignoreExpressionErrors;
    @XmlAttribute(name = "joinDiscriminator")
    protected String joinDiscriminator;
    @XmlAttribute(name = "visible")
    protected Boolean visible;

    /**
     * Gets the value of the text property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the selector property.
     *
     * @return possible object is
     * {@link XmlSelector }
     */
    public XmlSelector getSelector() {
        return selector;
    }

    /**
     * Sets the value of the selector property.
     *
     * @param value allowed object is
     * {@link XmlSelector }
     */
    public void setSelector(XmlSelector value) {
        this.selector = value;
    }

    /**
     * Gets the value of the validator property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validator property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidator().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlValidator }
     */
    public List<XmlValidator> getValidator() {
        if (validator == null) {
            validator = new ArrayList<XmlValidator>();
        }
        return this.validator;
    }

    /**
     * Gets the value of the metadata property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadata().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlNameValuePair }
     */
    public List<XmlNameValuePair> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<XmlNameValuePair>();
        }
        return this.metadata;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the internalName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInternalName() {
        return internalName;
    }

    /**
     * Sets the value of the internalName property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setInternalName(String value) {
        this.internalName = value;
    }

    /**
     * Gets the value of the displayName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the valuePresent property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isValuePresent() {
        if (valuePresent == null) {
            return false;
        }
        else {
            return valuePresent;
        }
    }

    /**
     * Sets the value of the valuePresent property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setValuePresent(Boolean value) {
        this.valuePresent = value;
    }

    /**
     * Gets the value of the override property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isOverride() {
        if (override == null) {
            return true;
        }
        else {
            return override;
        }
    }

    /**
     * Sets the value of the override property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setOverride(Boolean value) {
        this.override = value;
    }

    /**
     * Gets the value of the defaultValue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the ignoreExpressionErrors property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isIgnoreExpressionErrors() {
        if (ignoreExpressionErrors == null) {
            return true;
        }
        else {
            return ignoreExpressionErrors;
        }
    }

    /**
     * Sets the value of the ignoreExpressionErrors property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setIgnoreExpressionErrors(Boolean value) {
        this.ignoreExpressionErrors = value;
    }

    /**
     * Gets the value of the joinDiscriminator property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getJoinDiscriminator() {
        if (joinDiscriminator == null) {
            return "item";
        }
        else {
            return joinDiscriminator;
        }
    }

    /**
     * Sets the value of the joinDiscriminator property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setJoinDiscriminator(String value) {
        this.joinDiscriminator = value;
    }

    /**
     * Gets the value of the visible property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isVisible() {
        if (visible == null) {
            return true;
        }
        else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

}
