//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * <p>Java class for XmlSelectArc complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlSelectArc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="arc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="backTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="if" type="{urn:appsecinc.com/js-workflow-extensions}XmlExitCondition" />
 *       &lt;attribute name="unless" type="{urn:appsecinc.com/js-workflow-extensions}XmlExitCondition" />
 *       &lt;attribute name="when" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlSelectArc")
public class XmlSelectArc
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "arc")
    protected String arc;
    @XmlAttribute(name = "to")
    protected String to;
    @XmlAttribute(name = "backTo")
    protected String backTo;
    @XmlAttribute(name = "if")
    protected XmlExitCondition _if;
    @XmlAttribute(name = "unless")
    protected XmlExitCondition unless;
    @XmlAttribute(name = "when")
    protected String when;

    /**
     * Gets the value of the arc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getArc() {
        return arc;
    }

    /**
     * Sets the value of the arc property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setArc(String value) {
        this.arc = value;
    }

    /**
     * Gets the value of the to property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the backTo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBackTo() {
        return backTo;
    }

    /**
     * Sets the value of the backTo property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setBackTo(String value) {
        this.backTo = value;
    }

    /**
     * Gets the value of the if property.
     *
     * @return possible object is
     * {@link XmlExitCondition }
     */
    public XmlExitCondition getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     *
     * @param value allowed object is
     * {@link XmlExitCondition }
     */
    public void setIf(XmlExitCondition value) {
        this._if = value;
    }

    /**
     * Gets the value of the unless property.
     *
     * @return possible object is
     * {@link XmlExitCondition }
     */
    public XmlExitCondition getUnless() {
        return unless;
    }

    /**
     * Sets the value of the unless property.
     *
     * @param value allowed object is
     * {@link XmlExitCondition }
     */
    public void setUnless(XmlExitCondition value) {
        this.unless = value;
    }

    /**
     * Gets the value of the when property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setWhen(String value) {
        this.when = value;
    }

}
