//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * <p>Java class for XmlTask complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlTask">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="category" type="{urn:appsecinc.com/js-workflow-extensions}XmlTaskCategory" />
 *       &lt;attribute name="essential" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlTask")
public class XmlTask
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "category")
    protected XmlTaskCategory category;
    @XmlAttribute(name = "essential")
    protected Boolean essential;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the category property.
     *
     * @return possible object is
     * {@link XmlTaskCategory }
     */
    public XmlTaskCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value allowed object is
     * {@link XmlTaskCategory }
     */
    public void setCategory(XmlTaskCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the essential property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isEssential() {
        if (essential == null) {
            return false;
        }
        else {
            return essential;
        }
    }

    /**
     * Sets the value of the essential property.
     *
     * @param value allowed object is
     * {@link Boolean }
     */
    public void setEssential(Boolean value) {
        this.essential = value;
    }

}
