//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;

/**
 * <p>Java class for XmlTimeout complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XmlTimeout">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="arc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="since" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlTimeout")
public class XmlTimeout
        implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "time", required = true)
    protected String time;
    @XmlAttribute(name = "arc")
    protected String arc;
    @XmlAttribute(name = "since")
    protected String since;

    /**
     * Gets the value of the time property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the arc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getArc() {
        return arc;
    }

    /**
     * Sets the value of the arc property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setArc(String value) {
        this.arc = value;
    }

    /**
     * Gets the value of the since property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSince() {
        return since;
    }

    /**
     * Sets the value of the since property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setSince(String value) {
        this.since = value;
    }

}
