//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.08 at 03:34:30 PM CST 
//

package com.trustwave.dbpjobservice.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for XmlTaskCategory.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="XmlTaskCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Prechecks"/>
 *     &lt;enumeration value="Audit"/>
 *     &lt;enumeration value="Pentest"/>
 *     &lt;enumeration value="Discovery"/>
 *     &lt;enumeration value="URR"/>
 *     &lt;enumeration value="DataWarehousing"/>
 *     &lt;enumeration value="Report"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "XmlTaskCategory")
@XmlEnum
public enum XmlTaskCategory {

    @XmlEnumValue("Prechecks")
    PRECHECKS("Prechecks"),
    @XmlEnumValue("Audit")
    AUDIT("Audit"),
    @XmlEnumValue("Pentest")
    PENTEST("Pentest"),
    @XmlEnumValue("Discovery")
    DISCOVERY("Discovery"),
    URR("URR"),
    @XmlEnumValue("DataWarehousing")
    DATA_WAREHOUSING("DataWarehousing"),
    @XmlEnumValue("Report")
    REPORT("Report"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    XmlTaskCategory(String v) {
        value = v;
    }

    public static XmlTaskCategory fromValue(String v) {
        for (XmlTaskCategory c : XmlTaskCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
